name: RolePlay
main: main.CrisPlay
version: 1.15
api-version: 1.13
commands:
  roleplay:
    description: Controls this plugin.
    aliases: [rp, role, rolep, rplay, crp, crisrp]
    usage: Try /rp help

permissions:
  crisrp.*:
    description: Gives access to all Cristichi's RolePlay commands
    children:
      crisrp.admin: true
      crisrp.use: true
  crisrp.use:
    description: Allows you to have stats
    default: true